### PR TITLE
added opam file so that dev repo can be opam pinned directly

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by xavierleroy** [comment]
I'm afraid of having to maintain and keep in sync two OPAM files, the one in the sources and the one in the OPAM package repository.  Is there a clever way to do this?

**Comment by UnixJunkie** [comment]
I don't know one way. I would say just maintain the one in your source tree and when you do a new release copy paste it into the opam repository.

**Comment by hcarty** [comment]
topkg can help automate that process. It would currently require switching to vanilla ocamlbuild or jbuilder to take full advantage though, if I understand correctly.

**Comment by rgrinberg** [comment]
I'm also in favour of including an opam file and have done so in my PR #5. @xavierleroy note that the opam file in the source repository is considered to be the "source of truth" and it is up to whoever edits it in opam-repository to make sure that the change indeed makes it to upstream (this repository).

**Comment by xavierleroy** [comment]
Now that we use Dune, the .opam file is automatically generated.

**Pull request closed without merging**
